#:kivy 1.8.0

<AlertScreen>:
    AlertGrid:
        rows:1
        cols:2
        spacing:10
        padding:10

        MessagesList:

        Button:
            background_normal: "Images/blank.png"
            on_press:
                root.manager.transition.direction = 'left'
                root.manager.current = 'main'
            text:"Back"
            color: 0,0,0,1
            font_size: 40
            size_hint: 0.25, 0.25

